version: "3"

vars:
  version: v0.0.14

tasks:
  build: >-
    docker build
    -t bulatsan/airc:{{.version}}
    -t bulatsan/airc:latest
    -f ./Dockerfile .

  buildx: >-
    docker run --privileged --rm tonistiigi/binfmt --install all &&
    docker buildx create --name airc &&
    docker buildx use airc &&
    docker buildx inspect --bootstrap

  push: >-
    docker buildx build
    --platform linux/amd64,linux/arm64,linux/arm/v7
    -t bulatsan/airc:{{.version}}
    -t bulatsan/airc:latest
    -f ./Dockerfile
    --push .
